// Eksempeldata. Bytt ut med kall til eget API/database når dere har det klart.
export const CATEGORIES = [
  { id: 'kafe', label: 'Kafé' },
  { id: 'restaurant', label: 'Restaurant' },
  { id: 'bar', label: 'Bar' },
  { id: 'butikk', label: 'Butikk' },
]

export const venues = [
  {
    id: 'crafty-dog',
    name: 'Crafty Dog',
    category: 'restaurant',
    address: 'Markveien 57, 0550 Oslo',
    lat: 59.9229,
    lng: 10.7589,
    rating: 5,
    reviewCount: 42,
    amenities: ['vannskaal', 'hundegodteri', 'uteservering', 'lov_innendors'],
    blurb: 'Populær kombinasjon av restaurant og håndverksølbar hvor hunder er velkomne.',
    photo: 'https://gotobooking.imgix.net/product_images/882/3EqWEDFwpUyezbYe9C8pL1nCAvT?w=1200&fit=max&auto=format,compress',
    website: 'https://www.visitoslo.com/eat/crafty-dog',
    instagram: 'https://www.instagram.com/craftydogoslo/',
  },
  {
    id: 'bettola',
    name: 'Bettola',
    category: 'restaurant',
    address: 'Trondheimsveien 2, 0560 Oslo',
    lat: 59.9184,
    lng: 10.7194,
    rating: 4,
    reviewCount: 27,
    amenities: ['uteservering', 'inneservering', 'vannskaal'],
    blurb: 'Hunden er velkommen på denne stilige baren i bunnen av Grünerløkka.',
    photo: 'https://images.unsplash.com/photo-1544148103-0773bf10d330?w=800&q=80',
    website: 'https://www.bettola.no/',
    instagram: 'https://www.instagram.com/bettolaoslo/',
  },
  {
    id: 'parksalongen',
    name: 'Parksalongen',
    category: 'bar',
    address: 'Waldemar Thranes gate 1a, 0171 Oslo',
    lat: 59.9247,
    lng: 10.7583,
    rating: 4,
    reviewCount: 19,
    amenities: ['lov_innendors', 'vannskaal'],
    blurb: 'Kul og avslappet nabolagsbar der stamgjestene ofte har med bikkja under bordet.',
    photo: 'https://scontent.fosl5-1.fna.fbcdn.net/v/t39.30808-6/486622948_1201648098629130_3316908954405969458_n.jpg?stp=dst-jpg_tt6&cstp=mx2048x1238&ctp=s2048x1238&_nc_cat=103&_nc_map=urlgen_bucketless&ccb=1-7&_nc_sid=cc71e4&_nc_ohc=PStBxyy44NEQ7kNvwE4y2Xs&_nc_oc=AdonM2QLO4Jb8leSTx29TpYRSpRRlDczohs1KNsIYGdsMW1Un2rWoVrPMS0mOLvo948&_nc_zt=23&_nc_ht=scontent.fosl5-1.fna&_nc_gid=s42nNNM4UtaM4Qc9Tx71mQ&_nc_ss=7b2a8&oh=00_AQIXRVmW57-v8rx7K0sd3_qmQu3z1gf8pkAZ3BBi4Htxjg&oe=6AB15DCF',
    website: 'https://parksalongen.no/',
    instagram: 'https://www.instagram.com/parksalongenbar/',
  },
  {
    id: 'faerten-dyrebutikk',
    name: 'Færten Dyrebutikk',
    category: 'butikk',
    address: 'Bogstadveien 21, 0355 Oslo',
    lat: 59.9276,
    lng: 10.7157,
    rating: 5,
    reviewCount: 63,
    amenities: ['vannskaal', 'hundegodteri', 'lov_innendors'],
    blurb: 'Dyrebutikk hvor hunden får prøvesmake godbiter i kassa.',
    photo: 'https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=800&q=80',
    website: 'https://faertendyrebutikk.no/',
    instagram: 'https://www.instagram.com/faertendyrebutikk/',
  },
  {
    id: 'solsiden-kafe',
    name: 'Solsiden Kaffebar',
    category: 'kafe',
    address: 'Damstredet 8, 0177 Oslo',
    lat: 59.9219,
    lng: 10.7495,
    rating: 3,
    reviewCount: 11,
    amenities: ['uteservering'],
    blurb: 'Hyggelig uteservering i solveggen, men trangt å komme forbi innendørs.',
    photo: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=800&q=80',
    website: 'https://solsidenkafe.no/',
    instagram: 'https://www.instagram.com/solsidenkafe/',
  },
  {
    id: 'havna-restaurant',
    name: 'Havna Sjømatrestaurant',
    category: 'restaurant',
    address: 'Rådhusbrygge 2, 0250 Oslo',
    lat: 59.9106,
    lng: 10.7325,
    rating: 4,
    reviewCount: 34,
    amenities: ['uteservering', 'vannskaal', 'lov_innendors'],
    blurb: 'Store lokaler med god avstand mellom bordene, populært blant hundeeiere på tur langs sjøen.',
    photo: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&q=80',
    website: 'https://www.havna.no/',
    instagram: 'https://www.instagram.com/havnaoslo/',
  },
  {
id: 'espresso-house',
name: 'Espresso House',
category: 'cafe',
address: 'Flere lokasjoner i Oslo',
lat: 59.9139,
lng: 10.7522,
rating: 5,
reviewCount: 1,
amenities: ['lov_innendors'],
blurb: 'Alle Espresso House-kafeer ønsker hunder velkommen innendørs, så lenge det ikke oppstår hensyn til allergi eller ubehag hos ansatte eller gjester.',
photo: '',
website: 'https://espressohouse.zendesk.com/hc/no/articles/4506747248412-Kan-jeg-ta-med-meg-hunden-min-til-kaffebarene-deres-',
instagram: '',
},
{
id: 'winther-aker-brygge',
name: 'Winther Aker Brygge',
category: 'restaurant',
address: 'Grundingen 3, 0250 Oslo',
lat: 59.9106,
lng: 10.7278,
rating: 5,
reviewCount: 1,
amenities: ['lov_innendors'],
blurb: 'Winther opplyser at hunder er velkomne på alle restaurantene deres.',
photo: '',
website: 'https://www.wintherrestaurant.no/akerbrygge',
instagram: '',
},
{
id: 'winther-frognerparken',
name: 'Winther Frognerparken',
category: 'restaurant',
address: 'Middelthunsgate 17P, 0368 Oslo',
lat: 59.9318,
lng: 10.7084,
rating: 5,
reviewCount: 1,
amenities: ['lov_innendors'],
blurb: 'Winther opplyser at hunder er velkomne på alle restaurantene deres.',
photo: '',
website: 'https://www.wintherrestaurant.no/frognerparken',
instagram: '',
},
{
id: 'hakone-coffee-toyen',
name: 'Hakone Coffee Tøyen',
category: 'cafe',
address: 'Økernveien 9, 0653 Oslo',
lat: 59.9155,
lng: 10.7782,
rating: 5,
reviewCount: 1,
amenities: ['lov_innendors'],
blurb: 'Populær kaffebar hvor gjester rapporterer at hunder er velkomne innendørs.',
photo: '',
website: 'https://www.hakone.no/',
instagram: '',
},
{
id: 'stockfleths-gamlebyen',
name: 'Stockfleths Gamlebyen',
category: 'cafe',
address: 'Munkegata 2, 0656 Oslo',
lat: 59.9056,
lng: 10.7681,
rating: 5,
reviewCount: 1,
amenities: ['lov_innendors'],
blurb: 'Kaffebar i Gamlebyen hvor hunder er velkomne innendørs.',
photo: '',
website: 'https://stockfleths.as/kaffebar/gamlebyen/',
instagram: '',
},
{
id: 'fuglen-coffee-roasters',
name: 'Fuglen Coffee Roasters',
category: 'restaurant',
address: 'St. Halvards gate 33, 0192 Oslo',
lat: 59.9059,
lng: 10.7706,
rating: 5,
reviewCount: 1,
amenities: ['lov_innendors'],
blurb: 'Tekst kommer.',
photo: '',
website: 'https://www.fuglencoffee.no/',
instagram: '',
},
{
id: 'preik-gastrobar',
name: 'Preik Gastrobar',
category: 'restaurant',
address: 'St. Halvards gate 2, 0192 Oslo',
lat: 59.9054,
lng: 10.7688,
rating: 5,
reviewCount: 1,
amenities: ['lov_innendors'],
blurb: 'Hundevennlig gastrobar på Grønland.',
photo: '',
website: '',
instagram: 'https://www.instagram.com/preikoslo/',
},
{
id: 'mad-love-pizza',
name: 'Mad Love Pizza',
category: 'restaurant',
address: 'Grønlandsleiret 61B, 0190 Oslo',
lat: 59.9106,
lng: 10.7651,
rating: 5,
reviewCount: 1,
amenities: ['lov_innendors'],
blurb: 'Tekst kommer.',
photo: '',
website: 'https://madlove.no/',
instagram: '',
},
{
id: 'skrenten-pizza',
name: 'Skrenten Pizza',
category: 'restaurant',
address: 'Alnafetgata 1B, 0192 Oslo',
lat: 59.9076,
lng: 10.7730,
rating: 5,
reviewCount: 1,
amenities: ['lov_innendors', 'uteservering'],
blurb: 'Skikkelig god pizza hvor hunden kan hvile pent under bordet.',
photo: '',
website: 'https://www.skrentenpizza.no/',
instagram: '',
},
{
id: 'papegoye',
name: 'Papegøye',
category: 'restaurant',
address: 'Urtegata 48, 0190 Oslo',
lat: 59.9144,
lng: 10.7653,
rating: 5,
reviewCount: 1,
amenities: ['lov_innendors'],
blurb: 'Tidligere kjent som Neongrut. Hundevennlig serveringssted på Grønland.',
photo: '',
website: 'https://www.prettybird.no/',
instagram: '',
},
{
id: 'bernies',
name: "Bernie's",
category: 'restaurant',
address: 'Schweigaards gate 50B, 0191 Oslo',
lat: 59.9106,
lng: 10.7647,
rating: 5,
reviewCount: 1,
amenities: ['lov_innendors'],
blurb: 'Tekst kommer.',
photo: '',
website: 'https://bernies.no/',
instagram: '',
},
{
id: 'ukultur',
name: 'Ukultur',
category: 'bar',
address: 'Schweigaards gate 53A, 0191 Oslo',
lat: 59.9108,
lng: 10.7650,
rating: 5,
reviewCount: 1,
amenities: ['lov_innendors'],
blurb: 'Lokal pub og konsertscene hvor hunder er velkomne.',
photo: '',
website: '',
instagram: 'https://www.instagram.com/ukultur.oslo/',
},
{
id: 'kumi',
name: 'KUMI',
category: 'restaurant',
address: 'Schweigaards gate 56A, 0191 Oslo',
lat: 59.9109,
lng: 10.7655,
rating: 5,
reviewCount: 1,
amenities: ['lov_innendors'],
blurb: 'Tekst kommer.',
photo: '',
website: 'https://kumi.no/',
instagram: '',
},
{
id: 'verdensrommet',
name: 'Verdensrommet',
category: 'bar',
address: 'Skippergata 24, 0154 Oslo',
lat: 59.9118,
lng: 10.7498,
rating: 5,
reviewCount: 1,
amenities: ['lov_innendors'],
blurb: 'Koselig bar i sentrum med øl, vin og drinker hvor hunder er velkomne.',
photo: '',
website: 'https://www.verdensrommet.world/about',
instagram: 'https://www.instagram.com/verdens_rommet/',
},
{
id: 'pastis-bistrobar',
name: 'Pastis Bistrobar',
category: 'restaurant',
address: 'Stranden 3, 0250 Oslo',
lat: 59.9098,
lng: 10.7268,
rating: 5,
reviewCount: 1,
amenities: ['lov_innendors'],
blurb: 'Tekst kommer.',
photo: '',
website: 'https://www.pastisbistrobar.no/',
instagram: '',
},
{
id: 'panu-restaurant',
name: 'Panu Restaurant',
category: 'restaurant',
address: 'St. Olavs plass 3, 0165 Oslo',
lat: 59.9194,
lng: 10.7388,
rating: 5,
reviewCount: 1,
amenities: ['lov_innendors'],
blurb: 'Hund er velkommen ved forhåndsavtale med restauranten.',
photo: '',
website: 'https://www.restaurant-panu.com/',
instagram: 'https://www.instagram.com/panu_oslo',
},
]

export const AMENITY_LABELS = {
  vannskaal: 'Vannskål',
  hundegodteri: 'Hundegodteri',
  uteservering: 'Uteservering',
  lov_innendors: 'Lov å ta med innendørs',
}
